#page title
page_title: Allah App # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: https://play.google.com/store/apps/details?id=com.demo.light_switch # Enter Google Play Store URL.
presskit_download_link:
  /privacypolicy/ # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/logo.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Allah App # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Free # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Guide to make you visualize word 'Allah' in your heart <br>  زیرو کے سفید بلب پر پیلے رنگ سے ’اللہ‘ لکھیں ، اُسے سونے سے پہلے یا جاگتے  وقت آنکھوں میی سمونے کی کوشش کریں۔ جب آنکھوں میں آجائے تو پھر اُس لفظ کو دل پر اُتاریں ۔

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Universal Sufi Order
your_link: https://www.universalsufiorder.org/
your_city:
email_address: abidzaidi.dev@gmail.com
facebook_username:
instagram_username: abidzaidi7
twitter_username:
github_username: aliabidzaidi
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Visualize word Allah
    description: Five different device colors includedFive different device colors includedFive different device colors includedFive different device colors included
    fontawesome_icon_name: eye

  - title: Zero Watt Bulb On/Off
    description: Five different device colors includedFive different device colors includedFive different device colors includedFive different device colors included
    fontawesome_icon_name: lightbulb

  - title: Generate Divine Energy
    description: Five different device colors includedFive different device colors includedFive different device colors includedFive different device colors included
    fontawesome_icon_name: charging-station

  - title: # New Feature Title
    description: # New Feature Description
    fontawesome_icon_name: # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
